### ISSUE TITLE
Unable to create new credential

### ISSUE THREAD

**Issue by Quadrubo** [JYLN/n8n-nodes-ntfy#2]
I am unable to create a new credential. The NTFY API doesn't show up in the dropdown.
I already tried restarting the instance.
This happens on the latest version of n8n.

![image](https://github.com/JYLN/n8n-nodes-ntfy/assets/71718414/a2e1c5c9-cf8c-4585-a66a-d59d07f838a9)

**Comment by JYLN** [comment]
@Quadrubo On a fresh local install of n8n and this NTFY node, I'm unable to replicate the issue. Could you provide a screenshot of the installed node within your community nodes? Also, does the node itself within the workflow allow you to create the credential?
