### ISSUE TITLE
Hope to add Icons

### ISSUE THREAD

**Issue by Yinr** [JYLN/n8n-nodes-ntfy#4]
Thank you for creating this excellent plugin.

I hope the [Icons](https://docs.ntfy.sh/publish/#icons) option can be added.

Thanks!

**Comment by JYLN** [comment]
@Yinr Thank you for the suggestion! I will work on adding on an `Icons` field into a future minor version.

For the meantime, the JSON notification construction will allow you to use an icon in your notification. Check the [wiki entry](https://github.com/JYLN/n8n-nodes-ntfy/wiki/Usage#json-and-binary-fields) for more information on how to use this

This issue will close out when I merge a pull request for the new field. I will keep you updated on when this is slated for release
